import java.util.HashMap;

class Data {
    /**
     * @return HashMap with offset name & pointer
     */
    HashMap<String, Integer> getOffsetHashMap(){
        HashMap<String, Integer> offsetPointer = new HashMap<>();
        offsetPointer.put("starter1", 119054);
        offsetPointer.put("starter2", 119071);
        offsetPointer.put("starter3", 119088);
        offsetPointer.put("rivalBattle1starter1", 238066);
        offsetPointer.put("rivalBattle1starter2", 238069);
        offsetPointer.put("rivalBattle1starter3", 238072);
        return offsetPointer;
    }

    /**
     * @return HashMap with Pokémon name & decimal value
     */
     HashMap<String, Byte> getPkmnHashMap() {
        HashMap<String, Byte> pkmnData = new HashMap<>();
        pkmnData.put("'M",(byte) 0);
        pkmnData.put("Rhydon", (byte) 1);
        pkmnData.put("Kangaskhan", (byte) 2);
        pkmnData.put("NidoranM", (byte) 3);
        pkmnData.put("Clefairy", (byte) 4);
        pkmnData.put("Spearow", (byte) 5);
        pkmnData.put("Voltorb", (byte) 6);
        pkmnData.put("Nidoking", (byte) 7);
        pkmnData.put("Slowbro", (byte) 8);
        pkmnData.put("Ivysaur", (byte) 9);
        pkmnData.put("Exeggutor", (byte) 10);
        pkmnData.put("Lickitung", (byte) 11);
        pkmnData.put("Exeggcute", (byte) 12);
        pkmnData.put("Grimer", (byte) 13);
        pkmnData.put("Gengar", (byte) 14);
        pkmnData.put("NidoranF", (byte) 15);
        pkmnData.put("Nidoqueen", (byte) 16);
        pkmnData.put("Cubone", (byte) 17);
        pkmnData.put("Rhyhorn", (byte) 18);
        pkmnData.put("Lapras", (byte) 19);
        pkmnData.put("Arcanine", (byte) 20);
        pkmnData.put("Mew", (byte) 21);
        pkmnData.put("Gyarados", (byte) 22);
        pkmnData.put("Shellder", (byte) 23);
        pkmnData.put("Tentacool", (byte) 24);
        pkmnData.put("Gastly", (byte) 25);
        pkmnData.put("Scyther", (byte) 26);
        pkmnData.put("Staryu", (byte) 27);
        pkmnData.put("Blastoise", (byte) 28);
        pkmnData.put("Pinsir", (byte) 29);
        pkmnData.put("Tangela", (byte) 30);
        pkmnData.put("MissingNo.", (byte) 31);
        pkmnData.put("Growlithe", (byte) 33);
        pkmnData.put("Onix", (byte) 34);
        pkmnData.put("Fearow", (byte) 35);
        pkmnData.put("Pidgey", (byte) 36);
        pkmnData.put("Slowpoke", (byte) 37);
        pkmnData.put("Kadabra", (byte) 38);
        pkmnData.put("Graveler", (byte) 39);
        pkmnData.put("Chansey", (byte) 40);
        pkmnData.put("Machoke", (byte) 41);
        pkmnData.put("Mr.Mime", (byte) 42);
        pkmnData.put("Hitmonlee", (byte) 43);
        pkmnData.put("Hitmonchan", (byte) 44);
        pkmnData.put("Arbok", (byte) 45);
        pkmnData.put("Parasect", (byte) 46);
        pkmnData.put("Psyduck", (byte) 47);
        pkmnData.put("Drowzee", (byte) 48);
        pkmnData.put("Golem", (byte) 49);
        pkmnData.put("Magmar", (byte) 51);
        pkmnData.put("Electabuzz", (byte) 53);
        pkmnData.put("Magneton", (byte) 54);
        pkmnData.put("Koffing", (byte) 55);
        pkmnData.put("Mankey", (byte) 57);
        pkmnData.put("Seel", (byte) 58);
        pkmnData.put("Diglett", (byte) 59);
        pkmnData.put("Tauros", (byte) 60);
        pkmnData.put("Farfetch'd", (byte) 64);
        pkmnData.put("Venonat", (byte) 65);
        pkmnData.put("Dragonite", (byte) 66);
        pkmnData.put("Doduo", (byte) 70);
        pkmnData.put("Poliwag", (byte) 71);
        pkmnData.put("Jynx", (byte) 72);
        pkmnData.put("Moltres", (byte) 73);
        pkmnData.put("Articuno", (byte) 74);
        pkmnData.put("Zapdos", (byte) 75);
        pkmnData.put("Ditto", (byte) 76);
        pkmnData.put("Meowth", (byte) 77);
        pkmnData.put("Vulpix", (byte) 82);
        pkmnData.put("Ninetales", (byte) 83);
        pkmnData.put("Pikachu", (byte) 84);
        pkmnData.put("Raichu", (byte) 85);
        pkmnData.put("Dratini", (byte) 88);
        pkmnData.put("Dragonair", (byte) 89);
        pkmnData.put("Kabuto", (byte) 90);
        pkmnData.put("Kabutops", (byte) 91);
        pkmnData.put("Horsea", (byte) 92);
        pkmnData.put("Seadra", (byte) 93);
        pkmnData.put("Sandshrew", (byte) 96);
        pkmnData.put("Sandslash", (byte) 97);
        pkmnData.put("Omanyte", (byte) 98);
        pkmnData.put("Omastar", (byte) 99);
        pkmnData.put("Jigglypuff", (byte) 100);
        pkmnData.put("Wigglytuff", (byte) 101);
        pkmnData.put("Eevee", (byte) 102);
        pkmnData.put("Flareon", (byte) 103);
        pkmnData.put("Jolteon", (byte) 104);
        pkmnData.put("Vaporeon", (byte) 105);
        pkmnData.put("Machop", (byte) 106);
        pkmnData.put("Zubat", (byte) 107);
        pkmnData.put("Ekans", (byte) 108);
        pkmnData.put("Paras", (byte) 109);
        pkmnData.put("Poliwhirl", (byte) 110);
        pkmnData.put("Poliwrath", (byte) 111);
        pkmnData.put("Weedle", (byte) 112);
        pkmnData.put("Kakuna", (byte) 113);
        pkmnData.put("Beedrill", (byte) 114);
        pkmnData.put("Dodrio", (byte) 116);
        pkmnData.put("Primeape", (byte) 117);
        pkmnData.put("Dugtrio", (byte) 118);
        pkmnData.put("Venomoth", (byte) 119);
        pkmnData.put("Dewgong", (byte) 120);
        pkmnData.put("Caterpie", (byte) 123);
        pkmnData.put("Metapod", (byte) 124);
        pkmnData.put("Butterfree", (byte) 125);
        pkmnData.put("Machamp", (byte) 126);
        pkmnData.put("Golduck", (byte) 128);
        pkmnData.put("Hypno", (byte) 129);
        pkmnData.put("Golbat", (byte) 130);
        pkmnData.put("Mewtwo", (byte) 131);
        pkmnData.put("Snorlax", (byte) 132);
        pkmnData.put("Magikarp", (byte) 133);
        pkmnData.put("Muk", (byte) 136);
        pkmnData.put("Kingler", (byte) 138);
        pkmnData.put("Cloyster", (byte) 139);
        pkmnData.put("Electrode", (byte) 141);
        pkmnData.put("Clefable", (byte) 142);
        pkmnData.put("Weezing", (byte) 143);
        pkmnData.put("Persian", (byte) 144);
        pkmnData.put("Marowak", (byte) 145);
        pkmnData.put("Haunter", (byte) 147);
        pkmnData.put("Abra", (byte) 148);
        pkmnData.put("Alakazam", (byte) 149);
        pkmnData.put("Pidgeotto", (byte) 150);
        pkmnData.put("Pidgeot", (byte) 151);
        pkmnData.put("Starmie", (byte) 152);
        pkmnData.put("Bulbasaur", (byte) 153);
        pkmnData.put("Venusaur", (byte) 154);
        pkmnData.put("Tentacruel", (byte) 155);
        pkmnData.put("Goldeen", (byte) 157);
        pkmnData.put("Seaking", (byte) 158);
        pkmnData.put("Ponyta", (byte) 163);
        pkmnData.put("Rapidash", (byte) 164);
        pkmnData.put("Rattata", (byte) 165);
        pkmnData.put("Raticate", (byte) 166);
        pkmnData.put("Nidorino", (byte) 167);
        pkmnData.put("Nidorina", (byte) 168);
        pkmnData.put("Geodude", (byte) 169);
        pkmnData.put("Porygon", (byte) 170);
        pkmnData.put("Aerodactyl", (byte) 171);
        pkmnData.put("Magnemite", (byte) 173);
        pkmnData.put("Charmander", (byte) 176);
        pkmnData.put("Squirtle", (byte) 177);
        pkmnData.put("Charmeleon", (byte) 178);
        pkmnData.put("Wartortle", (byte) 179);
        pkmnData.put("Charizard", (byte) 180);
        pkmnData.put("Ghost", (byte) 184);
        pkmnData.put("Oddish", (byte) 185);
        pkmnData.put("Gloom", (byte) 186);
        pkmnData.put("Vileplume", (byte) 187);
        pkmnData.put("Bellsprout", (byte) 188);
        pkmnData.put("Weepinbell", (byte) 189);
        pkmnData.put("Victreebel", (byte) 190);
        return pkmnData;
    }
}
